services:
  trumpornot:
    image: thibaldocker/trumpornot:latest
    ports:
      - "8080:8080"
    environment:
      - EXTENSION_API_KEY=${EXTENSION_API_KEY}
      - ADMIN_PAGE_KEY=${ADMIN_PAGE_KEY}
      - BETA_PAGE_KEY=${BETA_PAGE_KEY}
      - EVENTS_API_URL=${EVENTS_API_URL}
      - EVENTS_API_KEY=${EVENTS_API_KEY}
      - PORT=8080
      - DB_DIR=/app/backend/data
    volumes:
      - sqlite-data:/app/backend/data
    restart: unless-stopped

volumes:
  sqlite-data:
